#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'

require 'strscan'

module EDTF
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 145)

  def parse(input)
    @yydebug = !!ENV['DEBUG']
    scan(input)
    do_parse
  end
  
  def next_token
    @stack.shift
  end

  def on_error(tid, val, vstack)
    warn "failed to parse extended date time %s (%s) %s" % [val.inspect, token_to_str(tid) || '?', vstack.inspect]
  end

  def scan(input)
    @src = StringScanner.new(input)
    @stack = []
    tokenize
  end

  private

  def tokenize
    until @src.eos?
      case
      when @src.scan(/T/)
        @stack << [:T, @src.matched]
      when @src.scan(/Z/)
        @stack << [:Z, @src.matched]
      when @src.scan(/\+/)
        @stack << [:PLUS, @src.matched]
      when @src.scan(/-/)
        @stack << [:MINUS, @src.matched]
      when @src.scan(/:/)
        @stack << [:COLON, @src.matched]
      when @src.scan(/\//)
        @stack << [:SLASH, @src.matched]
      when @src.scan(/\d/)
        @stack << [['D', @src.matched].join.intern, @src.matched]
      else @src.scan(/./)
        @stack << [:UNMATCHED, @src.rest]
      end
    end
  
    @stack
  end


# -*- racc -*-
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    11,    42,    43,    13,    15,    16,    17,    18,    19,    20,
    21,    22,    23,    11,   127,   128,    13,    15,    16,    17,
    18,    19,    20,    21,    22,    23,   116,    15,    16,    17,
    18,    19,    20,    21,    22,    23,    13,    15,    16,    17,
    18,    19,    20,    21,    22,    23,    13,    15,    16,    17,
    18,    19,    20,    21,    22,    23,    13,    15,    16,    17,
    18,    19,    20,    21,    22,    23,    13,    15,    16,    17,
    18,    19,    20,    21,    22,    23,   113,    15,    16,    17,
    18,    19,    20,    21,    22,    23,   141,    15,    16,    17,
    18,    19,    20,    21,    22,    23,   114,    15,    16,    17,
    18,    19,    20,    21,    22,    23,    13,    15,    16,    17,
    18,    19,    20,    21,    22,    23,    13,    15,    16,    17,
    18,    19,    20,    21,    22,    23,    13,    15,    16,    17,
    18,    19,    20,    21,    22,    23,    13,    15,    16,    17,
    18,    19,    20,    21,    22,    23,    61,    15,    16,    17,
    18,    19,    20,    21,    22,    23,    56,    57,    58,    59,
   117,   118,   119,   120,   121,   122,    63,    71,    64,    68,
    65,    69,    66,    67,    70,    15,    16,    17,    18,    19,
    20,    21,    22,    23,    25,   100,    38,    91,   102,    26,
    90,    38,    91,    94,    95,    96,    90,    38,    91,    94,
    95,    96,   100,    38,    91,    94,    95,    96,   138,    38,
    91,    94,    95,    96,    90,    38,    91,    94,    95,    96,
    56,    57,    58,    59,    55,   109,   110,   111,   112,   108,
   100,    38,    91,   105,    51,    53,    52,   100,    38,    91,
    73,    75,    74,    37,    38,    35,    83,    82,    87,    82,
   126,   -38,   -33,   -39,   -37,   107,   -36,   -35,   -32,   115,
   -31,   -30,   -29,   -28,    98,   -34,    78,    77,   127,    76,
   130,   131,   132,    54,   135,   136,    30,    27,   139,   140,
    24,   142,   143 ]

racc_action_check = [
     0,    27,    27,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,    26,   102,   102,    26,    26,    26,    26,
    26,    26,    26,    26,    26,    26,    90,    90,    90,    90,
    90,    90,    90,    90,    90,    90,    96,    96,    96,    96,
    96,    96,    96,    96,    96,    96,    11,    11,    11,    11,
    11,    11,    11,    11,    11,    11,    12,    12,    12,    12,
    12,    12,    12,    12,    12,    12,    49,    49,    49,    49,
    49,    49,    49,    49,    49,    49,    83,    83,    83,    83,
    83,    83,    83,    83,    83,    83,   138,   138,   138,   138,
   138,   138,   138,   138,   138,   138,    87,    87,    87,    87,
    87,    87,    87,    87,    87,    87,    29,    29,    29,    29,
    29,    29,    29,    29,    29,    29,    95,    95,    95,    95,
    95,    95,    95,    95,    95,    95,    94,    94,    94,    94,
    94,    94,    94,    94,    94,    94,    38,    38,    38,    38,
    38,    38,    38,    38,    38,    38,    37,    37,    37,    37,
    37,    37,    37,    37,    37,    37,    91,    91,    91,    91,
    91,    91,    91,    91,    91,    91,    42,    42,    42,    42,
    42,    42,    42,    42,    42,   100,   100,   100,   100,   100,
   100,   100,   100,   100,     3,    76,    76,    76,    76,     3,
    54,    54,    54,    54,    54,    54,   115,   115,   115,   115,
   115,   115,   131,   131,   131,   131,   131,   131,   132,   132,
   132,   132,   132,   132,   107,   107,   107,   107,   107,   107,
    35,    35,    35,    35,    35,    82,    82,    82,    82,    82,
    77,    77,    77,    77,    32,    32,    32,    78,    78,    78,
    43,    43,    43,    25,    25,    25,    52,    52,    53,    53,
    98,    75,    73,    71,    70,    81,    69,    68,    67,    88,
    66,    65,    64,    63,    55,    74,    46,    45,   105,    44,
   108,   113,   114,    33,   126,   130,    24,     8,   135,   136,
     1,   139,   142 ]

racc_action_pointer = [
    -5,   280,   nil,   182,   nil,   nil,   nil,   nil,   272,   nil,
   nil,    38,    48,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   276,   235,     8,    -7,   nil,    98,
   nil,   nil,   231,   267,   nil,   212,   nil,   138,   128,   nil,
   nil,   nil,   157,   232,   264,   262,   261,   nil,   nil,    58,
   nil,   nil,   238,   240,   182,   258,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   258,   257,   256,   255,   253,   252,   251,
   249,   248,   nil,   247,   260,   246,   177,   222,   229,   nil,
   nil,   249,   217,    68,   nil,   nil,   nil,    88,   253,   nil,
    18,   148,   nil,   nil,   118,   108,    28,   nil,   242,   nil,
   166,   nil,     6,   nil,   nil,   260,   nil,   206,   264,   nil,
   nil,   nil,   nil,   265,   266,   188,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   266,   nil,   nil,   nil,
   267,   194,   200,   nil,   nil,   272,   271,   nil,    78,   273,
   nil,   nil,   274,   nil ]

racc_action_default = [
    -1,   -91,    -2,    -3,    -4,    -5,    -6,    -7,    -8,    -9,
   -10,   -91,   -91,   -49,   -50,   -51,   -52,   -53,   -54,   -55,
   -56,   -57,   -58,   -59,   -91,   -91,   -91,   -91,   -11,   -91,
   144,   -12,   -13,   -91,   -16,   -91,   -45,   -91,   -91,   -73,
   -48,   -27,   -91,   -91,   -91,   -91,   -91,   -43,   -44,   -91,
   -14,   -18,   -91,   -91,   -91,   -91,   -68,   -69,   -70,   -71,
   -66,   -72,   -67,   -51,   -53,   -55,   -57,   -58,   -54,   -56,
   -59,   -52,   -60,   -61,   -63,   -62,   -91,   -91,   -91,   -26,
   -19,   -91,   -91,   -91,   -64,   -20,   -21,   -91,   -91,   -46,
   -91,   -91,   -74,   -85,   -91,   -91,   -91,   -90,   -91,   -40,
   -91,   -81,   -91,   -83,   -41,   -91,   -42,   -91,   -91,   -61,
   -62,   -63,   -65,   -91,   -91,   -91,   -89,   -75,   -76,   -77,
   -78,   -79,   -80,   -86,   -87,   -88,   -91,   -82,   -84,   -23,
   -91,   -91,   -91,   -15,   -47,   -91,   -91,   -25,   -91,   -91,
   -24,   -22,   -91,   -17 ]

racc_goto_table = [
    60,    29,    88,     3,     1,    72,   101,   101,   106,   103,
   104,    80,    86,   137,   137,    33,    32,   133,    49,    34,
    31,    85,    50,    28,    47,    41,    44,    62,    45,    40,
    46,    48,    99,     5,     4,    36,   134,     2,    79,    39,
   nil,   nil,   nil,   nil,   nil,   nil,    72,   nil,   nil,   nil,
    72,   nil,   nil,    60,   nil,   129,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    60,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   123,   124,   125,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    60 ]

racc_goto_check = [
    34,    22,    15,     3,     1,    34,    31,    31,    31,    30,
    30,    18,    18,    21,    21,    14,    12,    16,    22,    17,
    11,    19,    13,     6,    23,    24,    25,    22,    26,     3,
    27,    28,    29,     5,     4,    32,    33,     2,    22,    35,
   nil,   nil,   nil,   nil,   nil,   nil,    34,   nil,   nil,   nil,
    34,   nil,   nil,    34,   nil,    15,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    34,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    22,    22,    22,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    34 ]

racc_goto_pointer = [
   nil,     4,    37,     3,    34,    33,    12,   nil,   nil,   nil,
   nil,    -5,    -9,   -10,   -10,   -52,   -98,    -6,   -41,   -32,
   nil,  -118,   -11,    -3,    -2,    -1,     1,     3,     4,   -44,
   -67,   -70,    10,   -79,   -37,    14 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,     6,     7,     8,     9,
    10,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    81,    97,    12,   nil,    84,   nil,   nil,   nil,   nil,   nil,
   nil,    93,   nil,    89,    14,    92 ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 20, :_reduce_none,
  1, 20, :_reduce_none,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 22, :_reduce_none,
  1, 22, :_reduce_none,
  1, 25, :_reduce_8,
  1, 25, :_reduce_9,
  1, 25, :_reduce_10,
  2, 26, :_reduce_11,
  3, 23, :_reduce_12,
  1, 30, :_reduce_none,
  2, 30, :_reduce_14,
  5, 31, :_reduce_15,
  1, 31, :_reduce_none,
  8, 36, :_reduce_17,
  1, 32, :_reduce_18,
  2, 32, :_reduce_19,
  2, 32, :_reduce_20,
  1, 38, :_reduce_none,
  5, 38, :_reduce_22,
  3, 37, :_reduce_23,
  5, 37, :_reduce_24,
  4, 37, :_reduce_25,
  4, 27, :_reduce_26,
  1, 42, :_reduce_none,
  2, 44, :_reduce_28,
  2, 44, :_reduce_29,
  2, 44, :_reduce_30,
  2, 44, :_reduce_31,
  2, 44, :_reduce_32,
  2, 44, :_reduce_33,
  2, 44, :_reduce_34,
  2, 45, :_reduce_35,
  2, 45, :_reduce_36,
  2, 45, :_reduce_37,
  2, 45, :_reduce_38,
  2, 46, :_reduce_39,
  3, 47, :_reduce_40,
  3, 47, :_reduce_41,
  3, 47, :_reduce_42,
  3, 28, :_reduce_43,
  3, 29, :_reduce_44,
  1, 33, :_reduce_none,
  1, 34, :_reduce_none,
  1, 35, :_reduce_none,
  3, 24, :_reduce_48,
  1, 41, :_reduce_49,
  1, 41, :_reduce_none,
  1, 53, :_reduce_51,
  1, 53, :_reduce_52,
  1, 53, :_reduce_53,
  1, 53, :_reduce_54,
  1, 53, :_reduce_55,
  1, 53, :_reduce_56,
  1, 53, :_reduce_57,
  1, 53, :_reduce_58,
  1, 53, :_reduce_59,
  2, 43, :_reduce_60,
  2, 43, :_reduce_61,
  2, 43, :_reduce_62,
  2, 43, :_reduce_63,
  1, 39, :_reduce_none,
  2, 39, :_reduce_65,
  2, 54, :_reduce_66,
  2, 54, :_reduce_67,
  2, 54, :_reduce_68,
  2, 54, :_reduce_69,
  2, 54, :_reduce_70,
  2, 54, :_reduce_71,
  2, 51, :_reduce_72,
  1, 51, :_reduce_none,
  1, 50, :_reduce_none,
  2, 50, :_reduce_75,
  2, 50, :_reduce_76,
  2, 50, :_reduce_77,
  2, 50, :_reduce_78,
  2, 50, :_reduce_79,
  2, 50, :_reduce_80,
  1, 49, :_reduce_none,
  2, 49, :_reduce_82,
  1, 48, :_reduce_none,
  2, 48, :_reduce_84,
  1, 40, :_reduce_none,
  2, 40, :_reduce_86,
  2, 40, :_reduce_87,
  2, 40, :_reduce_88,
  2, 52, :_reduce_89,
  1, 52, :_reduce_none ]

racc_reduce_n = 91

racc_shift_n = 144

racc_token_table = {
  false => 0,
  :error => 1,
  :T => 2,
  :Z => 3,
  :PLUS => 4,
  :MINUS => 5,
  :COLON => 6,
  :SLASH => 7,
  :D0 => 8,
  :D1 => 9,
  :D2 => 10,
  :D3 => 11,
  :D4 => 12,
  :D5 => 13,
  :D6 => 14,
  :D7 => 15,
  :D8 => 16,
  :D9 => 17,
  :UNMATCHED => 18 }

racc_nt_base = 19

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "T",
  "Z",
  "PLUS",
  "MINUS",
  "COLON",
  "SLASH",
  "D0",
  "D1",
  "D2",
  "D3",
  "D4",
  "D5",
  "D6",
  "D7",
  "D8",
  "D9",
  "UNMATCHED",
  "$start",
  "edtf",
  "level_0_expression",
  "date",
  "date_time",
  "level_0_interval",
  "positive_date",
  "negative_date",
  "year",
  "year_month",
  "year_month_day",
  "time",
  "base_time",
  "zone_offset",
  "hour",
  "minute",
  "second",
  "midnight",
  "zone_offset_hour",
  "positive_zone_offset",
  "d01_13",
  "d01_59",
  "digit",
  "month",
  "d01_12",
  "long_month",
  "short_month",
  "february",
  "month_day",
  "d01_31",
  "d01_30",
  "d01_29",
  "d00_23",
  "d00_59",
  "positive_digit",
  "d01_23" ]

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

module_eval(<<'.,.,', 'parser.y', 22)
  def _reduce_8(val, _values, result)
     result = Date.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 23)
  def _reduce_9(val, _values, result)
     result = Date.new(*val.flatten) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 24)
  def _reduce_10(val, _values, result)
     result = Date.new(*val.flatten) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 26)
  def _reduce_11(val, _values, result)
     result = Date.new(-1 * val[1].year, val[1].month, val[1].day) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 29)
  def _reduce_12(val, _values, result)
     result = DateTime.new(val[0].year, val[0].month, val[0].day, *val[2]) 
    result
  end
.,.,

# reduce 13 omitted

module_eval(<<'.,.,', 'parser.y', 32)
  def _reduce_14(val, _values, result)
     result = val.flatten 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 34)
  def _reduce_15(val, _values, result)
     result = [val[0], val[2], val[4]] 
    result
  end
.,.,

# reduce 16 omitted

module_eval(<<'.,.,', 'parser.y', 37)
  def _reduce_17(val, _values, result)
     result = [24, 0, 0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 39)
  def _reduce_18(val, _values, result)
     result = 0 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 40)
  def _reduce_19(val, _values, result)
     result = -1 * val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 41)
  def _reduce_20(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 21 omitted

module_eval(<<'.,.,', 'parser.y', 44)
  def _reduce_22(val, _values, result)
     result = 0 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 47)
  def _reduce_23(val, _values, result)
     result = Rational(val[0] * 60 + val[2], 1440) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 48)
  def _reduce_24(val, _values, result)
     result = Rational(840, 1440) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 49)
  def _reduce_25(val, _values, result)
     result = Rational(val[3], 1440) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 51)
  def _reduce_26(val, _values, result)
     result = val.zip([1000,100,10,1]).reduce(0) { |s,(a,b)| s += a * b } 
    result
  end
.,.,

# reduce 27 omitted

module_eval(<<'.,.,', 'parser.y', 55)
  def _reduce_28(val, _values, result)
     result = 1  
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 56)
  def _reduce_29(val, _values, result)
     result = 3  
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 57)
  def _reduce_30(val, _values, result)
     result = 5  
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 58)
  def _reduce_31(val, _values, result)
     result = 7  
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 59)
  def _reduce_32(val, _values, result)
     result = 8  
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 60)
  def _reduce_33(val, _values, result)
     result = 10 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 61)
  def _reduce_34(val, _values, result)
     result = 12 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 63)
  def _reduce_35(val, _values, result)
     result = 4  
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 64)
  def _reduce_36(val, _values, result)
     result = 6  
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 65)
  def _reduce_37(val, _values, result)
     result = 9  
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 66)
  def _reduce_38(val, _values, result)
     result = 11 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 68)
  def _reduce_39(val, _values, result)
     result = 2 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 70)
  def _reduce_40(val, _values, result)
     result = [val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 71)
  def _reduce_41(val, _values, result)
     result = [val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 72)
  def _reduce_42(val, _values, result)
     result = [val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 74)
  def _reduce_43(val, _values, result)
     result = [val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 76)
  def _reduce_44(val, _values, result)
     result = val[0,1] + val[2] 
    result
  end
.,.,

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

module_eval(<<'.,.,', 'parser.y', 84)
  def _reduce_48(val, _values, result)
     result = val[0] ... val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 86)
  def _reduce_49(val, _values, result)
     result = 0 
    result
  end
.,.,

# reduce 50 omitted

module_eval(<<'.,.,', 'parser.y', 89)
  def _reduce_51(val, _values, result)
     result = 1 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 90)
  def _reduce_52(val, _values, result)
     result = 2 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 91)
  def _reduce_53(val, _values, result)
     result = 3 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 92)
  def _reduce_54(val, _values, result)
     result = 4 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 93)
  def _reduce_55(val, _values, result)
     result = 5 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 94)
  def _reduce_56(val, _values, result)
     result = 6 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 95)
  def _reduce_57(val, _values, result)
     result = 7 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 96)
  def _reduce_58(val, _values, result)
     result = 8 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 97)
  def _reduce_59(val, _values, result)
     result = 9 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 99)
  def _reduce_60(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 100)
  def _reduce_61(val, _values, result)
     result = 10 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 101)
  def _reduce_62(val, _values, result)
     result = 11 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 102)
  def _reduce_63(val, _values, result)
     result = 12 
    result
  end
.,.,

# reduce 64 omitted

module_eval(<<'.,.,', 'parser.y', 105)
  def _reduce_65(val, _values, result)
     result = 13 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 107)
  def _reduce_66(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 108)
  def _reduce_67(val, _values, result)
     result = 10 + val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 109)
  def _reduce_68(val, _values, result)
     result = 20 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 110)
  def _reduce_69(val, _values, result)
     result = 21 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 111)
  def _reduce_70(val, _values, result)
     result = 22 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 112)
  def _reduce_71(val, _values, result)
     result = 23 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 114)
  def _reduce_72(val, _values, result)
     result = 0  
    result
  end
.,.,

# reduce 73 omitted

# reduce 74 omitted

module_eval(<<'.,.,', 'parser.y', 118)
  def _reduce_75(val, _values, result)
     result = 24 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 119)
  def _reduce_76(val, _values, result)
     result = 25 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 120)
  def _reduce_77(val, _values, result)
     result = 26 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 121)
  def _reduce_78(val, _values, result)
     result = 27 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 122)
  def _reduce_79(val, _values, result)
     result = 28 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 123)
  def _reduce_80(val, _values, result)
     result = 29 
    result
  end
.,.,

# reduce 81 omitted

module_eval(<<'.,.,', 'parser.y', 126)
  def _reduce_82(val, _values, result)
     result = 30 
    result
  end
.,.,

# reduce 83 omitted

module_eval(<<'.,.,', 'parser.y', 129)
  def _reduce_84(val, _values, result)
     result = 31 
    result
  end
.,.,

# reduce 85 omitted

module_eval(<<'.,.,', 'parser.y', 132)
  def _reduce_86(val, _values, result)
     result = 30 + val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 133)
  def _reduce_87(val, _values, result)
     result = 40 + val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 134)
  def _reduce_88(val, _values, result)
     result = 50 + val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 136)
  def _reduce_89(val, _values, result)
     result = 0 
    result
  end
.,.,

# reduce 90 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module EDTF
