name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    environment: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        coverage:
          - false
        ruby-version:
          - '3.3'
          - '3.2'
          - 'jruby'
        include:
          - ruby-version: '4.0'
            coverage: true

    steps:
      - name: Git checkout
        uses: actions/checkout@v7

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake

      - name: Upload coverage results
        if: matrix.coverage
        continue-on-error: true
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}
